title: ADVEC
subtitle: "ADVEC @ 2017"
description: "ADVEC @ 2017."
author: LIUG
timezone: UTC
url: https://advec.org
root: /
permalink: :title/
public_dir: dest/
code_dir: downloads/code
highlight:
  enable: true
  line_number: false
per_page: 0

theme: advec

facebook: advecoficial
instagram: advecoficial
twitter: advecoficial
youtube: advitoriaemcristo
